---
- hosts: localhost
  become: yes
  tasks:
  - name: copy
    shell:
      cmd: 'scp -P 22 -p /data/jenkins/workspace/prov_vmpile/target/devops-1.0.war pileUser@40.114.211.179:/home/pileUser/'

- hosts: my_hosts
  become: yes
  roles:
   - role_java
   
  tasks:
  - name: deploy and launch war
    shell:
      cmd: 'java -jar /home/pileUser/devops-1.0.war'
      #cmd: 'ssh -T pileUser@40.114.211.179 -p22 -f "java -jar /home/pileUser/devops-1.0.war"'
       
